const { types, format } = require("util");
// console.log(types);
/* { isExternal: [Function: isExternal],
    isDate: [Function: isDate],
    isArgumentsObject: [Function: isArgumentsObject],
    isBigIntObject: [Function: isBigIntObject],      
    isBooleanObject: [Function: isBooleanObject],    
    isNumberObject: [Function: isNumberObject],      
    isStringObject: [Function: isStringObject],      
    isSymbolObject: [Function: isSymbolObject],      
    isNativeError: [Function: isNativeError],        
    isRegExp: [Function: isRegExp],
    isAsyncFunction: [Function: isAsyncFunction],    
    isGeneratorFunction: [Function: isGeneratorFunction],
    isGeneratorObject: [Function: isGeneratorObject],
    isPromise: [Function: isPromise],
    isMap: [Function: isMap],
    isSet: [Function: isSet],
    isMapIterator: [Function: isMapIterator],
    isSetIterator: [Function: isSetIterator],
    isWeakMap: [Function: isWeakMap],
    isWeakSet: [Function: isWeakSet],
    isArrayBuffer: [Function: isArrayBuffer],
    isDataView: [Function: isDataView],
    isSharedArrayBuffer: [Function: isSharedArrayBuffer],
    isProxy: [Function: isProxy],
    isWebAssemblyCompiledModule: [Function: isWebAssemblyCompiledModule],
    isModuleNamespaceObject: [Function: isModuleNamespaceObject],
    isAnyArrayBuffer: [Function: isAnyArrayBuffer],
    isBoxedPrimitive: [Function: isBoxedPrimitive],
    isArrayBufferView: [Function: isView],
    isTypedArray: [Function: isTypedArray],
    isUint8Array: [Function: isUint8Array],
    isUint8ClampedArray: [Function: isUint8ClampedArray],
    isUint16Array: [Function: isUint16Array],
    isUint32Array: [Function: isUint32Array],
    isInt8Array: [Function: isInt8Array],
    isInt16Array: [Function: isInt16Array],
    isInt32Array: [Function: isInt32Array],
    isFloat32Array: [Function: isFloat32Array],
    isFloat64Array: [Function: isFloat64Array],
    isBigInt64Array: [Function: isBigInt64Array],
    isBigUint64Array: [Function: isBigUint64Array] } */

console.log(format("{sssssssssssdasda:fss}"));
